variable "az_env" {}
variable "az" {}
variable "az_vpc_id" {}
variable "az_igw_id" {}
variable "az_cidr_block_public" {}
variable "az_cidr_block_web" {}
variable "az_cidr_block_app" {}
variable "az_cidr_block_data" {}
variable "az_nat_ami" {}
variable "az_nat_instance_type" {}
variable "az_nat_keyname" {}