variable "aws_region" { default = "us-east-1" }
variable "env" { default = "prod" }
variable "cidr_block" { default = "10.32.0.0/16" }
variable "az1" { default = "us-east-1a" }
variable "az2" { default = "us-east-1c" }
variable "az3" { default = "us-east-1d" }
variable "nat_ami"               { default = "ami-184dc970" }
variable "nat_instance_type"     { default = "t2.nano" }
variable "nat_keyname"           { default = "cweiblen-jobcase" }
variable "zone_id"               { default = "Z3AFETNY19QFZZ" }
variable "vpn_ami"               { default = "ami-60cd950a" }
variable "vpn_instance_type"     { default = "t2.micro"}
variable "default_keyname"       { default = "cweiblen-macbook" }
variable "bootstrap_bucket"      { default = "weiblen-invoke-terraform" }
